{
  "_ansible_check_mode": "False",
  "_ansible_debug": "False",
  "_ansible_diff": "False",
  "_ansible_keep_remote_files": "False",
  "_ansible_module_name": "ghetto_json",
  "_ansible_no_log": "False",
  "_ansible_remote_tmp": "~/.ansible/tmp",
  "_ansible_selinux_special_fs": "['fuse', 'nfs', 'vboxsf', 'ramfs', '9p']",
  "_ansible_shell_executable": "/bin/sh",
  "_ansible_socket": "None",
  "_ansible_syslog_facility": "LOG_USER",
  "_ansible_tmpdir": "/Users/nicolaumnu/.ansible/tmp/ansible-tmp-1585153766.16-266963283543987/",
  "_ansible_verbosity": 0,
  "_ansible_version": "2.6.5",
  "assets/js/routes/routes.js": "assets/js/routes/routes-5d27f20.js",
  "build-shop/css/theme/theme.min.css": "build-shop/css/theme/theme-96d1be2b4b.min.css",
  "build-shop/js/pages/account.js": "build-shop/js/pages/account-3d30717967.js",
  "build-shop/js/pages/category.js": "build-shop/js/pages/category-c0a1d302da.js",
  "build-shop/js/pages/checkout.js": "build-shop/js/pages/checkout-f3ea1b1ad8.js",
  "build-shop/js/pages/map-init.js": "build-shop/js/pages/map-init-324e900e9d.js",
  "build-shop/js/pages/messages_es.js": "build-shop/js/pages/messages_es-97aa8da9f9.js",
  "build-shop/js/pages/product_detail.js": "build-shop/js/pages/product_detail-4f0ba9b08d.js",
  "build-shop/js/pages/view_cart.js": "build-shop/js/pages/view_cart-3a5eee5557.js",
  "build-shop/js/theme/theme.js": "build-shop/js/theme/theme-245da74991.js",
  "build-shop/js/vendors/vendors.js": "build-shop/js/vendors/vendors-f73e0a0bf5.js",
  "build/css/pages/checkout/checkout.css": "build/css/pages/checkout/checkout-507748e1c9.css",
  "build/css/pages/checkout/invoice_list.css": "build/css/pages/checkout/invoice_list-383f4eff25.css",
  "build/css/vendors/formvalidation/formValidation.min.css": "build/css/vendors/formvalidation/formValidation-057d834af3.min.css",
  "build/js/pages/formutils.js": "build/js/pages/formutils-9498218434.js",
  "build/js/vendors/formvalidation/formValidation.js": "build/js/vendors/formvalidation/formValidation-5c08790eca.js",
  "build/js/vendors/formvalidation/formValidation.min.js": "build/js/vendors/formvalidation/formValidation-5f12cfbc92.min.js",
  "build/js/vendors/formvalidation/formValidation.popular.js": "build/js/vendors/formvalidation/formValidation-bcba9fdd39.popular.js",
  "build/js/vendors/formvalidation/framework/bootstrap.js": "build/js/vendors/formvalidation/framework/bootstrap-d32c5e763e.js",
  "build/js/vendors/formvalidation/framework/bootstrap.min.js": "build/js/vendors/formvalidation/framework/bootstrap-94729587e3.min.js",
  "build/js/vendors/formvalidation/framework/bootstrap4.js": "build/js/vendors/formvalidation/framework/bootstrap4-71783658bd.js",
  "build/js/vendors/formvalidation/framework/bootstrap4.min.js": "build/js/vendors/formvalidation/framework/bootstrap4-b42408b69a.min.js"
}